/*
 * Copyright 2005-2010 Ignis Software Tools Ltd. All rights reserved.
 */
package jsystem.extensions.report.html.summary;

public class Chapter extends Tag {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8629851296296715619L;

	String name = null;

	String objectives = null;

	Table table = null;

	public Chapter(String name, String objectives, Table table) {
		super("P");
		this.name = name;
		this.objectives = objectives;
		this.table = table;

		Tag header = new Tag("H2");
		header.add(name);
		add(header);

		if (objectives != null) {
			Tag objectTag = new Tag("H3");
			objectTag.add("Objectives");
			add(objectTag);
			Tag t = new Tag("P");
			t.add(objectives);
			add(t);
		}

		/*
		 * if (addResultTitle) { Tag r = new Tag("H3"); r.add(name + "
		 * results:"); add(r); }
		 */
		add(table);
	}

	/*
	 * public static void main(String[] args){ Chapter c = new
	 * Chapter("ASCII","objectives 1 2 3", Table.getExampleTable()); Tag html =
	 * new Tag("html"); Tag head = new Tag("head"); head.add(new Tag("link",
	 * "rel=stylesheet type=text/css href=./styles.css")); Tag title = new
	 * Tag("title"); title.add("HTML Calendar generated by Java HTML
	 * generator"); head.add(title); Tag body = new Tag("body"); Tag main = new
	 * Tag("div", "align=left"); body.add(main); main.add(c); main.add(new
	 * Tag("br", false)); html.add(head); html.add(body);
	 * System.out.println(html);
	 *  }
	 */
	/**
	 * @return Returns the table.
	 */
	public Table getTable() {
		return table;
	}

	/**
	 * @param table
	 *            The table to set.
	 */
	public void setTable(Table table) {
		this.table = table;
	}
}
