/*
 * Copyright 2005-2010 Ignis Software Tools Ltd. All rights reserved.
 */
package jsystem.extensions.report.html.summary;

public class Table extends Tag {

	private static final long serialVersionUID = 387981952761779137L;

	public Table(Object[][] table) {
		super("table", "WIDTH=50%");
		this.addAttribute(new Attribute("border", "1"));
		this.addAttribute(new Attribute("cellspacing", "2"));
		this.addAttribute(new Attribute("cellpadding", "2"));
		this
				.addAttribute(new Attribute("style",
						"'border-collapse:collapse;border:none;mso-border-alt:solid black .75pt;mso-padding-alt:0in 5.4pt 0in 5.4pt'"));
		// border=1 cellspacing=0 cellpadding=0
		// style='border-collapse:collapse;border:none;mso-border-alt:solid
		// black .75pt;mso-padding-alt:0in 5.4pt 0in 5.4pt'
		if (table != null && table.length > 0) {
			// int[] columSizes = getMaxCoulmSize(table);
			Object[] headerArray = table[0];
			Tag header = new Tag("tr");
			for (int i = 0; i < headerArray.length; i++) {
				Tag cell = new Tag("th", "class=header width=60 align=center");
				cell.add("&nbsp;");
				cell.add(headerArray[i]);
				header.add(cell);
			}
			add(header);
			for (int i = 1; i < table.length; i++) {
				addRow(table[i]);
			}
		}

	}

	public void addRow(Object[] row) {
		Tag tr = new Tag("tr", "align=center");
		for (int j = 0; j < row.length; j++) {
			Tag cell = new Tag("td", "align=left valign=center");
			cell.add("&nbsp;");
			if (row[j] == null) {
				row[j] = "";
			}
			cell.add(row[j]);
			tr.add(cell);
		}
		add(tr);
	}

	/*
	 * public static void main(String[] args){ Table t = getExampleTable(); Tag
	 * html = new Tag("html"); Tag head = new Tag("head"); head.add(new
	 * Tag("link", "rel=stylesheet type=text/css href=./styles.css")); Tag title =
	 * new Tag("title"); title.add("HTML Calendar generated by Java HTML
	 * generator"); head.add(title); Tag body = new Tag("body"); Tag main = new
	 * Tag("div", "align=left"); body.add(main); Tag h2 = new Tag("h2");
	 * main.add(h2); h2.add("HTML Calendar - an example for the Java HTML
	 * generator"); main.add(t); //main.add(table); main.add(new Tag("br",
	 * false)); main.add("&copy; 2000 Cyrille Artho"); Tag h3 = new Tag("h3");
	 * h3.add("This page was generated by the "); Tag link = new Tag("a",
	 * "href=http://artho.com/webtools/java/"); link.add("Java HTML generator");
	 * h3.add(link); main.add(h3); html.add(head); html.add(body);
	 * System.out.println(html); }
	 */

}
